"""initial_tables

Revision ID: cb7e63bcdf6e
Revises: 
Create Date: 2026-05-13 14:17:51.264328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7e63bcdf6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('yetkiler', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_index(op.f('ix_roller_id'), 'roller', ['id'], unique=False)
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('son_giris', sa.DateTime(timezone=True), nullable=True),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_kullanicilar_id'), 'kullanicilar', ['id'], unique=False)
    op.create_table('projeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('sahibi_id', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sahibi_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeler_id'), 'projeler', ['id'], unique=False)
    op.create_table('proje_uyeleri',
    sa.Column('proje_id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('atanma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.PrimaryKeyConstraint('proje_id', 'kullanici_id')
    )
    op.create_table('test_senaryolari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proje_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('json_icerik', sa.JSON(), nullable=False),
    sa.Column('versiyon', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['olusturan_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_senaryolari_id'), 'test_senaryolari', ['id'], unique=False)
    op.create_table('test_kosumlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senaryo_id', sa.Integer(), nullable=False),
    sa.Column('kosturan_kullanici', sa.Integer(), nullable=False),
    sa.Column('tetikleyici', sa.String(length=20), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('baslangic_zamani', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bitis_zamani', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sure_ms', sa.Integer(), nullable=True),
    sa.Column('tarayici_bilgisi', sa.String(length=100), nullable=True),
    sa.Column('ortam', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kosturan_kullanici'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['senaryo_id'], ['test_senaryolari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_kosumlari_id'), 'test_kosumlari', ['id'], unique=False)
    op.create_table('adim_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosum_id', sa.Integer(), nullable=False),
    sa.Column('adim_no', sa.Integer(), nullable=False),
    sa.Column('islem_turu', sa.String(length=50), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.Column('screenshot_yol', sa.String(length=500), nullable=True),
    sa.Column('sure_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kosum_id'], ['test_kosumlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adim_sonuclari_id'), 'adim_sonuclari', ['id'], unique=False)
    op.create_table('lighthouse_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosum_id', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('accessibility', sa.Float(), nullable=True),
    sa.Column('best_practice', sa.Float(), nullable=True),
    sa.Column('seo', sa.Float(), nullable=True),
    sa.Column('pwa', sa.Float(), nullable=True),
    sa.Column('tam_rapor', sa.JSON(), nullable=True),
    sa.Column('mod', sa.String(length=20), nullable=True),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kosum_id'], ['test_kosumlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lighthouse_sonuclari_id'), 'lighthouse_sonuclari', ['id'], unique=False)
    op.create_table('ai_receteler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kosum_id', sa.Integer(), nullable=False),
    sa.Column('adim_sonuc_id', sa.Integer(), nullable=True),
    sa.Column('hata_ozeti', sa.Text(), nullable=True),
    sa.Column('screenshot_yol', sa.String(length=500), nullable=True),
    sa.Column('gemini_modeli', sa.String(length=100), nullable=True),
    sa.Column('ai_analiz', sa.Text(), nullable=True),
    sa.Column('cozum_adimlari', sa.JSON(), nullable=True),
    sa.Column('ozguven_skoru', sa.Float(), nullable=True),
    sa.Column('kullanici_geri_bildirim', sa.String(length=20), nullable=True),
    sa.Column('olusturma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['adim_sonuc_id'], ['adim_sonuclari.id'], ),
    sa.ForeignKeyConstraint(['kosum_id'], ['test_kosumlari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_receteler_id'), 'ai_receteler', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_receteler_id'), table_name='ai_receteler')
    op.drop_table('ai_receteler')
    op.drop_index(op.f('ix_lighthouse_sonuclari_id'), table_name='lighthouse_sonuclari')
    op.drop_table('lighthouse_sonuclari')
    op.drop_index(op.f('ix_adim_sonuclari_id'), table_name='adim_sonuclari')
    op.drop_table('adim_sonuclari')
    op.drop_index(op.f('ix_test_kosumlari_id'), table_name='test_kosumlari')
    op.drop_table('test_kosumlari')
    op.drop_index(op.f('ix_test_senaryolari_id'), table_name='test_senaryolari')
    op.drop_table('test_senaryolari')
    op.drop_table('proje_uyeleri')
    op.drop_index(op.f('ix_projeler_id'), table_name='projeler')
    op.drop_table('projeler')
    op.drop_index(op.f('ix_kullanicilar_id'), table_name='kullanicilar')
    op.drop_table('kullanicilar')
    op.drop_index(op.f('ix_roller_id'), table_name='roller')
    op.drop_table('roller')
    # ### end Alembic commands ###
